<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="87908" started-at="2019-01-15T21:26:50Z" finished-at="2019-01-15T21:28:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="87908" started-at="2019-01-15T21:26:50Z" finished-at="2019-01-15T21:28:18Z">
      <class name="com.qa.meschino.testcases.verifyLogin">
        <test-method status="PASS" signature="startup()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@411f53a0]" name="startup" is-config="true" duration-ms="198" started-at="2019-01-15T16:26:51Z" finished-at="2019-01-15T16:26:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method status="SKIP" signature="LoginTest(java.util.Hashtable)[pri:0, instance:com.qa.meschino.testcases.verifyLogin@411f53a0]" name="LoginTest" duration-ms="27" started-at="2019-01-15T16:26:51Z" data-provider="getData" finished-at="2019-01-15T16:26:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Password=Test@123, Runmode=N, Expected=Success, UserName=neil@peter.com, Description=Verify that, system allows to login with valid Credentials, Result=, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping Test case  as runmode is No]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping Test case  as runmode is No
	at com.qa.meschino.testcases.verifyLogin.LoginTest(verifyLogin.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@411f53a0]" name="endTest" is-config="true" duration-ms="4416" started-at="2019-01-15T16:26:51Z" finished-at="2019-01-15T16:26:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="PASS" signature="startup()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@411f53a0]" name="startup" is-config="true" duration-ms="1" started-at="2019-01-15T16:26:55Z" finished-at="2019-01-15T16:26:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method status="PASS" signature="LoginTest(java.util.Hashtable)[pri:0, instance:com.qa.meschino.testcases.verifyLogin@411f53a0]" name="LoginTest" duration-ms="43810" started-at="2019-01-15T16:26:55Z" data-provider="getData" finished-at="2019-01-15T16:27:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Password=Test@123, Runmode=Y, Expected=Unsuccessfull, UserName=aneel@x.com, Description=Verify that, system does not allow to login with Invalid Credentials, Result=, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@411f53a0]" name="endTest" is-config="true" duration-ms="122" started-at="2019-01-15T16:27:39Z" finished-at="2019-01-15T16:27:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="FAIL" signature="LoginTest(java.util.Hashtable)[pri:0, instance:com.qa.meschino.testcases.verifyLogin@411f53a0]" name="LoginTest" duration-ms="37976" started-at="2019-01-15T16:27:39Z" data-provider="getData" finished-at="2019-01-15T16:28:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Password=Test@123, Runmode=Y, Expected=Success, UserName=qa@x.com, Description=Verify that, system does not allow to login with Invalid Credentials, Result=, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Verify that, system does not allow to login with Invalid Credentials]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Verify that, system does not allow to login with Invalid Credentials
	at junit.framework.Assert.fail(Assert.java:50)
	at com.qa.meschino.testcases.basetest.BaseTest.reportFailure(BaseTest.java:59)
	at com.qa.meschino.testcases.verifyLogin.LoginTest(verifyLogin.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="startup()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@411f53a0]" name="startup" is-config="true" duration-ms="0" started-at="2019-01-15T16:27:39Z" finished-at="2019-01-15T16:27:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@411f53a0]" name="endTest" is-config="true" duration-ms="99" started-at="2019-01-15T16:28:17Z" finished-at="2019-01-15T16:28:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@411f53a0]" name="close" is-config="true" duration-ms="827" started-at="2019-01-15T16:28:17Z" finished-at="2019-01-15T16:28:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.qa.meschino.testcases.verifyLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
