<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAP00396" name="com.qa.meschino.testcases.MyHRA_Male.VerifyHRAMaleRiskStatus" tests="1" failures="0" timestamp="1 Feb 2019 19:22:27 GMT" time="282.393" errors="1">
  <testcase name="HraMaleRiskStatus" time="282.393" classname="com.qa.meschino.testcases.MyHRA_Male.VerifyHRAMaleRiskStatus">
    <error type="java.lang.AssertionError" message="Risk not updated as expected">
      <![CDATA[java.lang.AssertionError: Risk not updated as expected
	at org.testng.Assert.fail(Assert.java:94)
	at com.qa.meschino.testcases.basetest.BaseTest.reportFailure(BaseTest.java:81)
	at com.qa.meschino.testcases.MyHRA_Male.VerifyHRAMaleRiskStatus.HraMaleRiskStatus(VerifyHRAMaleRiskStatus.java:364)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1194)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- HraMaleRiskStatus -->
</testsuite> <!-- com.qa.meschino.testcases.MyHRA_Male.VerifyHRAMaleRiskStatus -->
