<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAP00396" name="Default test" tests="3" failures="1" timestamp="15 Jan 2019 21:28:18 GMT" time="87.908" errors="0">
  <testcase name="LoginTest" time="0.027" classname="com.qa.meschino.testcases.verifyLogin">
    <skipped/>
  </testcase> <!-- LoginTest -->
  <testcase name="LoginTest" time="43.81" classname="com.qa.meschino.testcases.verifyLogin"/>
  <testcase name="LoginTest" time="37.976" classname="com.qa.meschino.testcases.verifyLogin">
    <failure type="junit.framework.AssertionFailedError" message="Verify that, system does not allow to login with Invalid Credentials">
      <![CDATA[junit.framework.AssertionFailedError: Verify that, system does not allow to login with Invalid Credentials
	at junit.framework.Assert.fail(Assert.java:50)
	at com.qa.meschino.testcases.basetest.BaseTest.reportFailure(BaseTest.java:59)
	at com.qa.meschino.testcases.verifyLogin.LoginTest(verifyLogin.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LoginTest -->
</testsuite> <!-- Default test -->
